name: Send custom JSON data to Slack workflow

# Tues @4am UTC
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Setup python 
        uses: actions/setup-python@v1
 
      - name: Install requirements 
        run: pip install -r ./telemetry-expiry/requirements.txt 
 
      # Temporary hard code project
      - name: Run telemetry probe expiry check 
        run: python ./telemetry-expiry/check_metrics.py -p focus-ios 

      - name: Run telemetry probe expiry check 
        run: ls -la
    
      - uses: actions/upload-artifact@v3
        with:
          name: slack-payload
          path: "./slack-payload.json"

      - name: Demo Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_ALERTS_SANDBOX }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
