name: testrail-api-tests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  push:
    paths:
      - 'testrail/**' # Run on changes to testrail directory
  pull_request:
    paths:
      - 'testrail/**' # Run on changes to testrail directory

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    env:
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_ALERTS_SANDBOX }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r testrail/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s testrail/tests -p '*tests.py'

    - name: Send Slack message on test result
      if: ${{ failure() }}
      id: slack-failure
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # slack message payload for failure
        payload: |
          {
            "text": "Test failed",
            "attachments": [
              {
                "color": "#FF0000",
                "title": "Test failed",
                "text": "Test failed in testrail-api-tests workflow",
                "fields": [
                  {
                    "title": "Job",
                    "value": "${{ github.job }}",
                    "short": true
                  },
                  {
                    "title": "Run ID",
                    "value": "${{ github.run_id }}",
                    "short": true
                  }
                ]
              }
            ]
          }
        

    - name: Send Slack message on test result
      if: ${{ success() }}
      id: slack-success
      uses: slackapi/slack-github-action@v1.26.0

