name: testrail-api-tests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  push:
    paths:
      - 'testrail/**' # Run on changes to testrail directory
  pull_request:
    paths:
      - 'testrail/**' # Run on changes to testrail directory

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    env:
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_ALERTS_SANDBOX }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r testrail/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s testrail/tests -p '*tests.py'

    - name: Send Slack message on test failure
      if: ${{ failure() }}
      id: slack-failure
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # payload with test failure output
        payload: |
          {
            "text": "Tests failed",
            "attachments": [
              {
                "color": "#FF0000",
                "title": "Test output",
                "text": "${{ job.status }}"
              }
            ]
          }
        

    - name: Send Slack message on test success
      if: ${{ success() }}
      id: slack-success
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # payload with test success output
        payload: |
          {
            "text": "Tests passed",
            "attachments": [
              {
                "color": "#00FF00",
                "title": "Test output",
                "text": "${{ job.status }}"
              }
            ]
          }

