name: TestRail Backup

on:
  workflow_dispatch:

jobs:
  test:
    name: Backup test suites
    runs-on: macos-14
    defaults:
      run:
        working-directory: ./backup-tools

    env:
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_ALERTS_SANDBOX }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch test cases
        run: |
          python backup_testrail.py

      - name: Establish Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          port: ${{ secrets.CLOUD_SQL_DATABASE_PORT }}
       
      - name: Upload to GCP bucket (todo)
        run: |
          today=`date "+%Y-%m-%d"`
          mkdir $today
          cp *.csv $today
          gcloud storage cp $today gs://backups-testrail-test-suites --recursive
          