name: testrail-api-tests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  push:
    paths:
      - 'testrail/**' # Run on changes to testrail directory
  pull_request:
    paths:
      - 'testrail/**' # Run on changes to testrail directory

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    env:
      TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
      TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TEST_ALERTS_SANDBOX }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r testrail/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s testrail/tests -p '*tests.py' > test_results.txt 2>&1

    - name: Send Slack message on test failure
      if: ${{ failure() }}
      id: slack-failure
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # payload with test failure output
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow:* ${{ github.workflow }}\n*Job:* ${{ github.job }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Status:* ${{ job.status }}\n*Test results:* Failed"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View results>"
                }
              }
            ]
          }
        

    - name: Send Slack message on test success
      if: ${{ success() }}
      id: slack-success
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # payload with slack blocks with job name, status, test results, test output, and url to view the results
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow:* ${{ github.workflow }}\n*Job:* ${{ github.job }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Status:* ${{ job.status }}\n*Test results:* Passed"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View results>"
                }
              }
            ]
          }
        